In [1]:
# Import Libraries
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression

# Load Dataset
df = pd.read_csv('/content/multiple_linear_regression_dataset.csv')

# Display First 5 Rows
print("First 5 Rows of Dataset:\n")
print(df.head())

# Dataset Shape
print("\nDataset Shape:")
print(df.shape)

# Dataset Columns
print("\nDataset Columns:")
print(df.columns)

# Define INPUT FEATURES (X)
X = df[[
    'Aptitude_Score',
    'Coding_Skill',
    'Communication_Skill',
    'Resume_Score',
    'Mock_Interview_Score'
]]

# Define OUTPUT/TARGET (y)
y = df['Placement_Readiness_Score']

# Create Multiple Linear Regression Model
model = LinearRegression()

# Train the Model
model.fit(X, y)

# Predict for New Students
new_students = pd.DataFrame({
    'Aptitude_Score': [80, 60, 95],
    'Coding_Skill': [75, 65, 90],
    'Communication_Skill': [70, 55, 92],
    'Resume_Score': [85, 70, 88],
    'Mock_Interview_Score': [90, 75, 96]
})

predictions = model.predict(new_students)

# Display Predictions
print("\nPredicted Placement Readiness Scores:\n")

for i in range(len(new_students)):
    print(f"Student {i+1}: {predictions[i]:.2f}")

# Model Accuracy
accuracy = model.score(X, y)

print("\nModel Accuracy:")
print(accuracy)

First 5 Rows of Dataset:

   Aptitude_Score  Coding_Skill  Communication_Skill  Resume_Score  \
0              42            92                   51            84   
1              91            67                   79            59   
2              59            60                   78            51   
3              88            43                   74            97   
4              57            85                   44            49   

   Mock_Interview_Score  Placement_Readiness_Score  
0                    89                         70  
1                    99                         76  
2                    38                         61  
3                    58                         68  
4                   100                         67  

Dataset Shape:
(100, 6)

Dataset Columns:
Index(['Aptitude_Score', 'Coding_Skill', 'Communication_Skill', 'Resume_Score',
       'Mock_Interview_Score', 'Placement_Readiness_Score'],
      dtype='object')

Predicted Placement Readines

In [2]:
# Import Pickle
import pickle

# Save Model Using Pickle
with open('placement_model_pickle', 'wb') as file:
    pickle.dump(model, file)

In [3]:
# Load Saved Model
with open('placement_model_pickle', 'rb') as file:
    mp = pickle.load(file)

In [4]:
mp.coef_

array([0.21366476, 0.32502126, 0.21214636, 0.10841244, 0.16819861])

In [5]:
mp.intercept_

np.float64(-2.281864358464375)

In [6]:
# Predict Placement Readiness Score
mp.predict([[80, 75, 70, 85, 90]])

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([78.39108764])

In [7]:
import joblib

In [8]:
# Save Model Using Joblib
joblib.dump(model, 'placement_model_joblib')

['placement_model_joblib']

In [9]:
# Load Saved Model
mj = joblib.load('placement_model_joblib')

In [10]:
mj.coef_

array([0.21366476, 0.32502126, 0.21214636, 0.10841244, 0.16819861])

In [11]:
mj.intercept_

np.float64(-2.281864358464375)

In [13]:
mj.predict([[80, 75, 70, 85, 90]])

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([78.39108764])